### PR TITLE
Fix duplicate person bug

### LINKED ISSUE #136: Patients and doctors with the same name cannot be added
When adding a patient with same name as a doctor, a duplicate error will be thrown. Names should not be de-duplicated across patients and doctors.

### PR DESCRIPTION
**Pull request by bmanara**
* Resolves #136 

Now able to add doctors and patients of the same name.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddDoctorCommand.java [hunk 1]
```diff
@@ -55,11 +55,11 @@ public AddDoctorCommand(Doctor doctor) {
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
 
-        if (model.hasPerson(doctorToAdd)) {
+        if (model.hasDoctor(doctorToAdd)) {
```
Comment (sam-theman88) [inline src/main/java/seedu/address/logic/commands/AddDoctorCommand.java:58]: Great use of inheritance to extend the functionality of the Person class through its child classes

Comment (sam-theman88) [reply src/main/java/seedu/address/logic/commands/AddDoctorCommand.java:58]: Applies to basically all the changes made in this PR
Awesome job being thorough and making all the relevant changes/updates!

**Review by sam-theman88 — APPROVED** [review]
LGTM
